### PR TITLE
fix: Update uppercase conversion to avoid '^' method which is not compatible with bash3.2

### PR DESCRIPTION
**Pull request by JonatV**

### CODE REVIEW

**Comment by itislu** [comment]
Also `${dir^^}` will have to be changed.

**Comment by JonatV** [comment]
I messed up a bit, I commit but had to update the branch to be up to date with 1.6.1. Still in the process to fully understand git

**Comment by itislu** [comment]
You can do the following to fix the commit history :)
1. `git pull origin main:main`
2. `git rebase main`

**Review by itislu — CHANGES_REQUESTED** [review]
No worries, you can do the following to fix the commit history on your `fix-uppercase` branch :)
1. `git pull origin main:main`
2. `git rebase main`
3. `git push --force`

**Review by itislu — APPROVED** [review]
Nice, thanks a lot!
I will squash the commits into one commit after merging :)

**Comment by JonatV** [comment]
My goodness I did it, I have to admit you're a boss with git GitHub aha

**Pull request merged**
